### ISSUE TITLE
Slack link is no longer active!

### ISSUE THREAD

**Issue by BaseMax** [jobream/500-Interview-Questions-CPP#16]
Hi there,

I would like to join the organization and PUSH some new programs/code.

## This link is no longer active

To join this workspace, you’ll need to ask the person who originally invited you for a new link.

```
https://jobream-slack.slack.com/join/shared_invite/zt-fuz8g3fl-S5tv99aE7uGSPcH~ou8Kfg
```

**Comment by MrSlimCoder** [comment]
@BaseMax We are not on slack now, If you want to join simply contribute to any of the repo and send us PR.
